name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

variables:
  - name: isReleaseBranch
    value: $[startsWith(variables['Build.SourceBranchName'], 'release_')]

pool:
  name: "Finance Terraform agent pool"

parameters:
  - name: Develop
    displayName: "Deploy Develop"
    type: boolean
    default: false

  - name: QA
    displayName: "Deploy QA"
    type: boolean
    default: false

  - name: Production
    displayName: "Deploy Production"
    type: boolean
    default: false

stages:

# ============================================================
# Build
# ============================================================

- stage: Build
  displayName: "Build"

  condition: |
    or(
      eq(variables['Build.Reason'], 'Manual'),
      eq(variables['Build.Reason'], 'PullRequest')
    )

  variables:
    - group: "Artifact Configurations"

  jobs:
    - job: Build
      displayName: "Build Inventory Data Application"

      workspace:
        clean: all

      steps:
        - checkout: self
          clean: true
          fetchDepth: 0

        - template: /pipeline-templates/build.yml
          parameters:
            backendSourcePath: "$(Build.SourcesDirectory)/Inventory.Data.Application/app/backend"

            frontendSourcePath: "$(Build.SourcesDirectory)/Inventory.Data.Application/app/frontend-react"

            frontendOutputPath: "$(Build.SourcesDirectory)/Inventory.Data.Application/app/frontend-react/dist"

            applicationSourcePath: "$(Build.SourcesDirectory)/Inventory.Data.Application"

            applicationPublishPath: "$(Build.ArtifactStagingDirectory)/application"

            artifactName: "application"

# ============================================================
# Develop
# ============================================================

- ${{ if parameters.Develop }}:
  - stage: Develop
    displayName: "Develop"
    dependsOn: Build

    condition: |
      and(
        succeeded(),
        eq(variables['Build.Reason'], 'Manual')
      )

    variables:
      - group: "Artifact Configurations"
      - group: "InventoryDataApplication Develop Configuration"

    jobs:

      - deployment: Deploy
        displayName: "Deploy"
        environment: "Develop"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/deploy.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-Dev"

                    applicationName: "app-inventory-data-app-dev"

                    artifactName: "application"

                    applicationDirectory: "$(Pipeline.Workspace)/application"

                    archivePath: "$(Pipeline.Workspace)/inventory-data-application.zip"

                    keyVaultName: "$(KeyVaultName)"

                    startupCommand: "gunicorn --chdir backend --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 wonder.main:app"

      - deployment: Version
        displayName: "Version"
        dependsOn: Deploy
        condition: succeeded()
        environment: "Develop"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/version.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-Dev"

                    applicationName: "app-inventory-data-app-dev"

                    keyVaultName: "$(KeyVaultName)"

                    environmentName: "dev"

# ============================================================
# QA
# ============================================================

- ${{ if parameters.QA }}:
  - stage: QA
    displayName: "QA"
    dependsOn: Build

    condition: |
      and(
        succeeded(),
        eq(variables['Build.Reason'], 'Manual')
      )

    variables:
      - group: "Artifact Configurations"
      - group: "InventoryDataApplication QA Configuration"

    jobs:

      - deployment: Deploy
        displayName: "Deploy"
        environment: "QA"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/deploy.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-QA"

                    applicationName: "app-inventory-data-app-qa"

                    artifactName: "application"

                    applicationDirectory: "$(Pipeline.Workspace)/application"

                    archivePath: "$(Pipeline.Workspace)/inventory-data-application.zip"

                    keyVaultName: "$(KeyVaultName)"

                    startupCommand: "gunicorn --chdir backend --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 wonder.main:app"

      - deployment: Version
        displayName: "Version"
        dependsOn: Deploy
        condition: succeeded()
        environment: "QA"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/version.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-QA"

                    applicationName: "app-inventory-data-app-qa"

                    keyVaultName: "$(KeyVaultName)"

                    environmentName: "qa"

# ============================================================
# Production
# ============================================================

- ${{ if and(parameters.QA, parameters.Production) }}:
  - stage: Production
    displayName: "Production"
    dependsOn: QA

    condition: |
      and(
        succeeded(),
        eq(variables['Build.Reason'], 'Manual'),
        eq(variables['isReleaseBranch'], 'True')
      )

    variables:
      - group: "Artifact Configurations"
      - group: "InventoryDataApplication Production Configuration"

    jobs:

      - deployment: Deploy
        displayName: "Deploy"
        environment: "Prod"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/deploy.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-Prod"

                    applicationName: "app-inventory-data-app-prod"

                    artifactName: "application"

                    applicationDirectory: "$(Pipeline.Workspace)/application"

                    archivePath: "$(Pipeline.Workspace)/inventory-data-application.zip"

                    keyVaultName: "$(KeyVaultName)"

                    startupCommand: "gunicorn --chdir backend --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 wonder.main:app"

      - deployment: Version
        displayName: "Version"
        dependsOn: Deploy
        condition: succeeded()
        environment: "Prod"

        workspace:
          clean: all

        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipeline-templates/version.yml
                  parameters:
                    azureSubscription: "Inventory-Data-App-Prod"

                    applicationName: "app-inventory-data-app-prod"

                    keyVaultName: "$(KeyVaultName)"

                    environmentName: "prod"