"""initial schema

Revision ID: d43ff7a17b74
Revises: 
Create Date: 2026-06-10 11:47:48.776186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43ff7a17b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=48), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=24), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=96), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('routed_team', sa.String(length=48), nullable=False),
    sa.Column('routed_assignee', sa.String(length=64), nullable=False),
    sa.Column('sub_team', sa.String(length=48), nullable=True),
    sa.Column('sub_assignee', sa.String(length=64), nullable=True),
    sa.Column('sub_assigned_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.String(length=32), nullable=False),
    sa.Column('first_run_date', sa.String(length=10), nullable=False),
    sa.Column('last_seen_run', sa.String(length=10), nullable=False),
    sa.Column('resolved_at', sa.String(length=32), nullable=True),
    sa.Column('recurrence', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_last_seen_run'), ['last_seen_run'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_status'), ['status'], unique=False)

    op.create_table('routing_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=48), nullable=False),
    sa.Column('assignee', sa.String(length=64), nullable=False),
    sa.Column('jira_project', sa.String(length=16), nullable=False),
    sa.Column('jira_component', sa.String(length=48), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_map_error_type'), ['error_type'], unique=False)

    op.create_table('rule',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('primitive', sa.String(length=24), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('target_table', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('fail_type', sa.String(length=8), nullable=False),
    sa.Column('owner_group', sa.String(length=48), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_error_type'), ['error_type'], unique=False)

    op.create_table('sla_target',
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('resolution_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('severity')
    )
    op.create_table('validation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('finished_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_scanned', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('autoclosed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_run_run_date'), ['run_date'], unique=False)

    op.create_table('ticket_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=24), nullable=True),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('actor', sa.String(length=48), nullable=False),
    sa.Column('occurred_at', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['error.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_event')
    with op.batch_alter_table('validation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_run_run_date'))

    op.drop_table('validation_run')
    op.drop_table('sla_target')
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_error_type'))

    op.drop_table('rule')
    with op.batch_alter_table('routing_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_map_error_type'))

    op.drop_table('routing_map')
    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_status'))
        batch_op.drop_index(batch_op.f('ix_error_severity'))
        batch_op.drop_index(batch_op.f('ix_error_last_seen_run'))
        batch_op.drop_index(batch_op.f('ix_error_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_error_error_type'))

    op.drop_table('error')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
